name: 'Test Insight'
description:
  'Reads a JSON file, processes test results, and saves processed data.'
author: 'Bruno Espino'

branding:
  icon: 'repeat'
  color: 'blue'

# Define your inputs here.
inputs:
  file:
    description: 'Path to the JSON file output from the automated test step'
    required: true

# Define your outputs here.
outputs:
  output:
    description: 'Output'

runs:
  using: node20
  main: dist/index.js
